# Generated by Django 5.0 on 2023-12-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spays", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="stripe_price_id",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
