# Generated by Django 4.2.8 on 2023-12-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spays", "0004_order_stripe_session_id_order_stripe_session_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "dtype",
                    models.CharField(
                        choices=[("Percentage", "percent"), ("Fixed", "fixed")],
                        max_length=32,
                    ),
                ),
                ("dval", models.DecimalField(decimal_places=2, max_digits=12)),
                ("stripe_id", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="discounts",
            field=models.ManyToManyField(to="spays.discount"),
        ),
    ]
